In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [16]:
data = pd.read_csv("../data/creditcard.csv")
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
data['normAmount']=StandardScaler().fit_transform(data['Amount'].values.reshape(-1,1))

In [19]:
data['Amount'].values.reshape(-1,1)

array([[ 149.62],
       [   2.69],
       [ 378.66],
       ...,
       [  67.88],
       [  10.  ],
       [ 217.  ]])

In [20]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,normAmount
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,0.244964
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,-0.342475
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,1.160686
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0.140534
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,-0.073403

In [21]:
data.drop(['Time','Amount'],axis=1,inplace=True)

In [22]:
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Class,normAmount
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0,0.244964
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0,-0.342475
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0,1.160686
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0,0.140534
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0,-0.073403

In [74]:
X=data.iloc[:,data.columns!='Class']
y=data.iloc[:,data.columns=='Class']

In [75]:
number_frauds=len(data[data['Class']==1])
fraud_indices= data[data['Class']==1].index

In [76]:
normal_indices=data[data['Class']==0].index
normal_indices_random=np.random.choice(normal_indices,number_frauds,replace=False)
normal_indices_random=np.array(normal_indices_random)

In [77]:
under_sample_indices=np.concatenate([fraud_indices,normal_indices_random])

In [78]:
X_undersample=X.iloc[under_sample_indices,:]

In [79]:
y_undersample=y.iloc[under_sample_indices,:]

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 0)
X_train_undersample, X_test_undersample, y_train_undersample, y_test_undersample = train_test_split(X_undersample,y_undersample,test_size = 0.3 ,random_state = 0)

In [81]:

from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import KFold, cross_val_score
from sklearn.metrics import confusion_matrix,precision_recall_curve,auc,roc_auc_score,roc_curve,recall_score,classification_report

In [84]:
def printing_Kfold_scores(x_train_data,y_train_data):
    fold = KFold(len(y_train_data),5,shuffle=False) 

    # Different C parameters
    c_param_range = [0.01,0.1,1,10,100]

    results_table = pd.DataFrame(index = range(len(c_param_range),2), columns = ['C_parameter','Mean recall score'])
    results_table['C_parameter'] = c_param_range

    # the k-fold will give 2 lists: train_indices = indices[0], test_indices = indices[1]
    j = 0
    for c_param in c_param_range:
        print('-------------------------------------------')
        print('C parameter: ', c_param)
        print('-------------------------------------------')
        print('')

        recall_accs = []
        for iteration, indices in enumerate(fold,start=1):
            print(j)
            X_train=x_train_data.iloc[indices[0],:]
            y_train=y_train_data.iloc[indices[0],:].values.ravel()
           
            # Call the logistic regression model with a certain C parameter
            lr = LogisticRegression(C = c_param, penalty = 'l1')

            # Use the training data to fit the model. In this case, we use the portion of the fold to train the model
            # with indices[0]. We then predict on the portion assigned as the 'test cross validation' with indices[1]
            
            lr.fit(X_train,y_train)

            # Predict values using the test indices in the training data
            y_pred_undersample = lr.predict(x_train_data.iloc[indices[1],:].values)

            # Calculate the recall score and append it to a list for recall scores representing the current c_parameter
            recall_acc = recall_score(y_train_data.iloc[indices[1],:].values,y_pred_undersample)
            recall_accs.append(recall_acc)
            print('Iteration ', iteration,': recall score = ', recall_acc)

        # The mean value of those recall scores is the metric we want to save and get hold of.
        results_table.ix[j,'Mean recall score'] = np.mean(recall_accs)
        j += 1
        print('')
        print('Mean recall score ', np.mean(recall_accs))
        print('')

    best_c = results_table.loc[results_table['Mean recall score'].idxmax()]['C_parameter']
    
    # Finally, we can check which C parameter is the best amongst the chosen.
    print('*********************************************************************************')
    print('Best model to choose from cross validation is with C parameter = ', best_c)
    print('*********************************************************************************')
    
    return best_c

In [85]:
len(X_train_undersample)

688

In [86]:
len(y_train_undersample)

688

In [87]:
printing_Kfold_scores(X_train_undersample,y_train_undersample)

-------------------------------------------
C parameter:  0.01
-------------------------------------------

0
Iteration  1 : recall score =  0.931506849315
0
Iteration  2 : recall score =  0.917808219178
0
Iteration  3 : recall score =  0.983050847458
0
Iteration  4 : recall score =  0.972972972973
0
Iteration  5 : recall score =  0.954545454545

Mean recall score  0.951976868694

-------------------------------------------
C parameter:  0.1
-------------------------------------------

1
Iteration  1 : recall score =  0.849315068493
1
Iteration  2 : recall score =  0.86301369863
1
Iteration  3 : recall score =  0.915254237288
1
Iteration  4 : recall score =  0.932432432432
1
Iteration  5 : recall score =  0.909090909091

Mean recall score  0.893821269187

-------------------------------------------
C parameter:  1
-------------------------------------------

2
Iteration  1 : recall score =  0.849315068493
2
Iteration  2 : recall score =  0.86301369863
2
Iteration  3 : recall score =  0.966101694915
2
Iteration  4 : recall score =  0.945945945946
2
Iteration  5 : recall score =  0.909090909091

Mean recall score  0.906693463415

-------------------------------------------
C parameter:  10
-------------------------------------------

3
Iteration  1 : recall score =  0.849315068493
3
Iteration  2 : recall score =  0.890410958904
3
Iteration  3 : recall score =  0.966101694915
3
Iteration  4 : recall score =  0.945945945946
3
Iteration  5 : recall score =  0.893939393939

Mean recall score  0.90914261244

-------------------------------------------
C parameter:  100
-------------------------------------------

4
Iteration  1 : recall score =  0.849315068493
4
Iteration  2 : recall score =  0.876712328767
4
Iteration  3 : recall score =  0.966101694915
4
Iteration  4 : recall score =  0.945945945946
4
Iteration  5 : recall score =  0.893939393939

Mean recall score  0.906402886412

*********************************************************************************
Best model to choose from cross validation is with C parameter =  0.01
*********************************************************************************

0.01